### ISSUE TITLE
大佬可以添加跳转网站的功能吗?

### ISSUE THREAD

**Issue by lsz7575** [harrynull/WoxDictionary#10]
例如 d good 然后按ALT+回车直接跳转到网站
https://forvo.com/word/good/#en
毕竟哑巴英语记单词根本记不住啊.
最好那个网址是可以自己配置的..方便其他人有更好的网址他自己修改..

或者您自己定义一个方案吧..

have a nice day..

**Comment by lsz7575** [comment]
按 Alt+Enter 即可复制单词

发现被占用了.. Σ( ° △ °|||)︴
那CTRL+Enter 吧..

**Comment by harrynull** [comment]
直接调用系统的语音库读单词可以吗？

**Comment by lsz7575** [comment]
> 直接调用系统的语音库读单词可以吗？

系统语音没有真人发得准啊.而且听着机器说挺难受得,真人发音有些会带点口音,接近真实环境.
网站慢点就慢点吧,但是人家读得准呀.而且有些小姐姐发音很好听, (o゜▽゜)o☆
听着机器音根本没有动力去学习,听着真人发音会觉得这个学了以后听得懂有点用有动力学习..大脑的奖励机制能触发..
forvo.com那个网站需要魔法上网才能用.

国内其实也有这些网站,
https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/good

https://www.youdict.com/w/good

简单的来说做成自定义跳转网址可以无限可能..但是做成系统语音很多词典都有这功能感觉没什么必要了..
如果您怕他们觉得有做广告嫌疑的话您可以直接只提供示例不提供网站呀..告诉他们怎么用就行..

**Comment by harrynull** [comment]
已经添加点进任意结果跳转网站功能，并顺带添加了按住Ctrl+Enter读出单词的功能

**Comment by harrynull** [comment]
https://github.com/harrynull/WoxDictionary/releases/tag/1.0.3
