### ISSUE TITLE
老哥，这个dist文件夹在哪儿下啊？是要编译之后吗？

### ISSUE THREAD

**Issue by sunencheng** [harrynull/WoxDictionary#11]
(手动安装) 复制 dist 文件夹到 C:\Users\\{User Name}\AppData\Local\Wox\app-{Version Number}\Plugins\

(Manual Installation) Copy dist folder to C:\Users\\{User Name}\AppData\Local\Wox\app-{Version Number}\Plugins\

**Comment by sunencheng** [comment]
另外，你的ecdict进行了双重压缩，这是为了安全吗？7z压缩一重就够了呀。

**Comment by sunencheng** [comment]
PS，那个ecdict.db可以另外选个位置嘛？对于C盘来说，现在压力很大，再丢进去一个800M 的着实不太妥帖啊。

**Comment by harrynull** [comment]
https://github.com/harrynull/WoxDictionary/releases/tag/1.0.3

当前不支持选择ecdict文件的位置。双重压缩是因为github不支持7z的文件扩展名

**Comment by sunencheng** [comment]
谢谢啦

**Comment by sunencheng** [comment]
![image](https://user-images.githubusercontent.com/8297524/88034648-95048380-cb73-11ea-856a-a025f7908d55.png)

**Comment by sunencheng** [comment]
已经重启了几次wox,发现无法生效，查询过，也没有冲突的好像.

**Comment by sunencheng** [comment]
正在尝试通过wpm方式安装，点击enter之后wox消失，后台有进程，现在估计正在下，卡住了

**Comment by sunencheng** [comment]
wpm安装报错 
You can help us to fix this issue by opening issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Sun\AppData\Roaming\Wox\Logs\1.4.1196\2020-07-21.txt
2. copy below exception message
Error id: 6e649563c45e4beea9fe271bc65033a4
Exception begin --------------------
  ICSharpCode.SharpZipLib.SharpZipBaseException: Unexpected EOF
  HResult: -2146233088
  Data: <System.Object> -> <>
  Source: ICSharpCode.SharpZipLib
  TargetAssembly: ICSharpCode.SharpZipLib, Version=1.2.0.246, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
  TargetModule: ICSharpCode.SharpZipLib.dll
  TargetSite: Void Fill()
  StackTrace: --------------------
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.BodyRead(Byte[] buffer, Int32 offset, Int32 count)
   at Wox.Core.Plugin.PluginInstaller.UnZip(String zipedFile, String strDirectory, Boolean overWrite) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:line 185
   at Wox.Core.Plugin.PluginInstaller.Install(String path) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:line 23
   at Wox.PublicAPIInstance.<>c__DisplayClass17_0.<InstallPlugin>b__0() in C:\projects\wox\Wox\PublicAPIInstance.cs:line 131
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_0.<ResultForInstallPlugin>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:line 175
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__17_7(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 209
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 07/21/2020 17:27:33
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.18362.0
* x64 OS: True
* x64 Process: True
* System Language: zh-CN
* Wox Language: zh-cn
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0
   * v4.8

## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Wox.exe)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\NLog.dll)
* Wox.Core, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Wox.Core.dll)
* Sentry, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Sentry.dll)
* Sentry.Protocol, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Sentry.Protocol.dll)
* System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\System.Collections.Immutable.dll)
* Wox.Infrastructure, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Wox.Infrastructure.dll)
* System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\System.Net.Http.dll)
* System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\System.ValueTuple.dll)
* Wox.Plugin, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Newtonsoft.Json.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\NuGet.Squirrel.dll)
* Wox.Plugin.BrowserBookmark, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.Caculator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Wox.Plugin.ControlPanel, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Color, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Folder, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.Sys, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\WindowsInput.dll)
* Wox.Plugin.Url, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\NHotkey.Wpf.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\System.Runtime.dll)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\CommandLine.dll)
* ToolGood.Words, Version=3.0.1.2, Culture=neutral, PublicKeyToken=d330f4fd115e6143 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\ToolGood.Words.dll)
* Microsoft.WindowsAPICodePack.Shell, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Microsoft.WindowsAPICodePack.Shell.dll)
* Microsoft.WindowsAPICodePack, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Microsoft.WindowsAPICodePack.dll)
* ICSharpCode.SharpZipLib, Version=1.2.0.246, Culture=neutral, PublicKeyToken=1b03e6acf1164f73 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\ICSharpCode.SharpZipLib.dll)
* Sentry.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\Sentry.PlatformAbstractions.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\Sun\AppData\Local\Wox\app-1.4.1196\System.Runtime.InteropServices.RuntimeInformation.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)

**Comment by harrynull** [comment]
wpm安装报错看上去是下载失败了。手动安装的话，词典有没有解压放到正确的位置？

**Comment by sunencheng** [comment]
1.已经放在正确位置。
![QQ图片20200723185059](https://user-images.githubusercontent.com/8297524/88279140-290e5080-cd16-11ea-9593-52ad7c47ad02.png)
2.重启之后可以看到插件。
![QQ图片20200723185353](https://user-images.githubusercontent.com/8297524/88279167-34617c00-cd16-11ea-8a72-a3afa223f6f5.png)
3.关键字无法响应。
![QQ图片20200723185435](https://user-images.githubusercontent.com/8297524/88279226-4511f200-cd16-11ea-80d0-c498660e3081.png)
4.对应目录没有存放ecdict.db的目录，不知道该怎么解决？
![QQ图片20200723185456](https://user-images.githubusercontent.com/8297524/88279261-565afe80-cd16-11ea-9ea8-648c7822fb90.png)

**Comment by harrynull** [comment]
1. 把 dist 文件夹剪切并重命名为 `C:\Users\用户名\AppData\Roaming\Wox\Plugins\WoxDictionary\`
2. 确保 C:\Users\用户名\AppData\Roaming\Wox\Plugins\WoxDictionary\dicts\ecdict.db 存在

**Comment by sunencheng** [comment]
ok，我明天试试，谢谢啦。

**Comment by sunencheng** [comment]
1.确保C:\Users\用户名\AppData\Roaming\Wox\Plugins\WoxDictionary\dicts\ecdict.db 存在
![image](https://user-images.githubusercontent.com/8297524/88356080-3b7d9e00-cd99-11ea-9742-14f99bc52334.png)
2.已经对dist文件夹进行了重命名。
![image](https://user-images.githubusercontent.com/8297524/88356151-741d7780-cd99-11ea-9c98-61a56d819cc3.png)
3.Wox重启后依然无法生效，请问是我哪里操作的不对吗？

**Comment by harrynull** [comment]
看我的第一步，你要把位于local的插件移到roaming文件夹里，再把ecdict.db复制到里面的dicts文件夹里。你应该是不需要手动新建dicts文件夹的，因为里面应该已经有一个txt文件了。

或者你可以试着把roaming的ecdict.db移到你local的插件里，理论上也应该可以。

**Comment by sunencheng** [comment]
1.把插件文件夹移动入roaming文件夹，并重命名，如图：
![image](https://user-images.githubusercontent.com/8297524/88371957-9fb75680-cdc7-11ea-8edc-11c9e9493321.png)
2.把ecdict.db复制到该目录下dicts文件夹(原来就存在),如图:
![image](https://user-images.githubusercontent.com/8297524/88371754-3a636580-cdc7-11ea-9377-a7945fefc349.png)
3.结果:移动完成后重启wox，setting不存在插件，且关键字d不起作用，如图:
![image](https://user-images.githubusercontent.com/8297524/88371869-71397b80-cdc7-11ea-9d38-8b31a464a6c9.png)
4.这是否和wox的portable mode有关系？

**Comment by sunencheng** [comment]
开了全局用wpm安装方式安装好了，移动了db文件，运行非常完美，谢谢啦。

**Comment by standin000** [comment]
> PS，那个ecdict.db可以另外选个位置嘛？对于C盘来说，现在压力很大，再丢进去一个800M 的着实不太妥帖啊。

@sunencheng 用scoop安装wox，可以把wox位置换了
