### ISSUE TITLE
can't translate en to ch

### ISSUE THREAD

**Issue by Rick0514** [harrynull/WoxDictionary#12]
I encounter a problem which is odd. I install the plugin and find it working normally at translating chinese into english. However when I input english words the plugins didn't word. I have downloaded the ecdict.7z and copied it to the folder like you said. But still didn't work. But translating chinese to english works perfectly though, even without the ecdict.7z. I am looking forward to your reply. thx!!

**Comment by harrynull** [comment]
Did you decompress ecdict.7z? You would eventually need ecdict.db

**Comment by Rick0514** [comment]
yes I decompress ecdict.7z, only got a 156MB file named ecdict.7z but no .db file. I also try to rename the file to ecdict.db but nothing has improved. do i miss some scripts to decode the file to a .db file??

**Comment by harrynull** [comment]
Try decompress it again. You can't get `ecdict.7z` out of `ecdict.7z`.

**Comment by Rick0514** [comment]
thanks a lot !!!!!!!!!!!!!!!!! The winrar attatched to WIN10 can't decompress the file. I downloaded another decompress software and fixed it.
