### ISSUE TITLE
能支持中文全角感叹号（！）吗？

### ISSUE THREAD

**Issue by ZeppLu** [harrynull/WoxDictionary#13]
如题，一般来说得输入`d exclamation!d`才能查看该词的英文释义，但如果输入`d exclamation！d`也能查看就好了，毕竟有时候打开wox时是中文输入法，支持全角叹号的话就能免去一次切换

**Comment by harrynull** [comment]
正常使用是不用手动输入感叹号的，从列表里选择词之后按回车会自动加上感叹号的。

**Comment by ZeppLu** [comment]
妙哉
