### ISSUE TITLE
关于wox

### ISSUE THREAD

**Issue by MuYanustc** [harrynull/WoxDictionary#15]
wox停更很久了，绝大多数插件都用不了了，现在只能当简单的启动器了。
您的插件下载wox直接崩溃。不知道是什么问题。
有别的windows下好的启动器推荐吗？

**Comment by harrynull** [comment]
建议你可以试一下wox fork出来的版本：https://github.com/Flow-Launcher/Flow.Launcher
以及为那个版本移植的本插件：https://github.com/harrynull/Flow.Launcher.Dictionary

**Comment by harrynull** [comment]
Closed due to inactivity.
