### ISSUE TITLE
翻译中文失效，英文可以

### ISSUE THREAD

**Issue by Burning1020** [harrynull/WoxDictionary#18]
![image](https://user-images.githubusercontent.com/25223859/131303377-dce9bb01-9808-45bf-991e-567dd8fd5794.png)

翻译中文的时候总是no results found，翻译英文可以拿到正确的结果，词库是下载你提供的，解压位置也正确

**Comment by harrynull** [comment]
有没有正确配置 API Token? 中文->英文是联网使用的 iciba 的服务，需要在插件的设置中填写相应的token。
此外，iciba好像暂时或永久关闭了新token的申请。见#16 。欢迎推荐合适的替代品。

**Comment by Burning1020** [comment]
多谢回复，已经不用这个了，以后有好的插件再试
