### ISSUE TITLE
为什么我输入wpm install Dictionary，进度条停止后，也没有下拉列表出现？

### ISSUE THREAD

**Issue by StarkL** [harrynull/WoxDictionary#3]
如题，
就算我wpm install 有道翻译也是如此？
求解。

**Comment by harrynull** [comment]
应当是属于Wox的问题，请到[Wox](https://github.com/Wox-launcher/Wox/issues)提交。

**Comment by standin000** [comment]
> 

@StarkL 你访问不了github，手工安装吧
