### ISSUE TITLE
Still cannot use !s after applied API Key.

### ISSUE THREAD

**Issue by AlphaTong** [harrynull/WoxDictionary#4]
Hi Harry. First of all, thank you for writting this beautiful tools. 

I've followed your guide and work for all feature instead of Synonym.

Could you help me?

**Comment by harrynull** [comment]
Hi, could you attach a screenshot to clarify what you mean by saying "Still cannot use" it. Does the words not pop out at all or only the translation is missing? Also, please make sure that you have copied [dist folder](https://github.com/harrynull/WoxDictionary/releases/tag/dict) to `C:\Users\\{User Name}\AppData\Local\Wox\app-{Version Number}\Plugins\`.

**Comment by harrynull** [comment]
Edit: You need to copy [ecdict.db](https://github.com/harrynull/WoxDictionary/releases/download/dict/ecdict.7z.zip) to `C:\Users\{your_user_name}\AppData\Roaming\Wox\Plugins\Dictionary-{random_characters}\dicts`.

**Comment by harrynull** [comment]
Closed due to inactivity.
