### ISSUE TITLE
Not working after installation through Wox package manager

### ISSUE THREAD

**Issue by WilCleaveland** [harrynull/WoxDictionary#5]
I can't get this plugin to work at all. I installed through the Wox package manager, entered my API key for Bighugelabs, and then restarted Wox. 

When I try to trigger with 'd' and type a word, nothing happens. 

What have I missed or done wrong? Thank you!

**Comment by harrynull** [comment]
Have you copied [ecdict.db](https://github.com/harrynull/WoxDictionary/releases/download/dict/ecdict.7z.zip) to `C:\Users\{your_user_name}\AppData\Roaming\Wox\Plugins\Dictionary-{random_characters}\dicts` ? You need to download and uncompress that manually.

**Comment by WilCleaveland** [comment]
Ok, I just downloaded that, extracted, and changed the file extension from .7z to .db. Then I put it in the folder you specified and restarted Wox. 

Still nothing. :(

I haven't gotten my own ICIBAToken, because I don't need Chinese translation. Could that be the problem? 

I went ahead and tried generating and ICIBAToken, but it still doesn't work.

**Comment by harrynull** [comment]
Don't change the file extension. Instead, extract that .7z file, and you will get ecdict.db.

**Comment by WilCleaveland** [comment]
Ah, I'm so dumb. Sorry, brand new Windows user after using OSX for years. Been a long time since I saw a .7z file or understood that I still had to extract it after unzipping the parent folder. 

Everything is working now, and this plugin ROCKS! Thank you so much for putting it together!

**Comment by WilCleaveland** [comment]
One more quick question: When I do synonyms, is this showing the Chinese translation? What would be necessary to tweak the plugin so it shows an English definition for the synonym instead? 
![image](https://user-images.githubusercontent.com/7683418/53343429-5dda6600-38de-11e9-971c-784d2e30378e.png)

**Comment by harrynull** [comment]
Yes, you do need to change the plugin a little bit to show English definition. The related code is located at [Dictionary.cs#L231](https://github.com/harrynull/WoxDictionary/blob/master/src/Dictionary.cs#L231).
Or, if you don't want to change the code, you can press enter to search for that highlighted synonyms instead.

**Comment by WilCleaveland** [comment]
Thank you! I'll see if I can figure out how to tweak the code. Really appreciate all your help and support on this! :)

**Comment by harrynull** [comment]
You're welcome :)

Wil Cleaveland <notifications@github.com> 于2019年2月26日周二 下午9:05写道：

**Comment by moonxkang** [comment]
hello - it wont let me move the db file over to the plugin /dict folder. any advice?
I am the owner + admin of this device. not sure why its not letting me do it 
![image](https://user-images.githubusercontent.com/77337767/104521431-e0e83080-55ca-11eb-8850-d73a5b077c2b.png)

**Comment by harrynull** [comment]
I am not sure either, and this does not seem to be related to this issue. Maybe try extract the files again to get a new copy, or check if there are any running programs using this folder.
