### ISSUE TITLE
option to turn off chinese?

### ISSUE THREAD

**Issue by jcpeterson** [harrynull/WoxDictionary#6]
could it be added?

**Comment by harrynull** [comment]
Hi, could you explain what do you mean to "turn off chinese?" Do you mean you only want English definition?

**Comment by jcpeterson** [comment]
Yes, that's how I'm using it (English dictionary only), and it works well.
I don't know of any comparable/working plugin to do that. I can see how it
wouldn't be a priority though.

**Comment by harrynull** [comment]
I have released a new version that provides an option to do that. Could you try it out and see if that is what you want?

To upgrade, simply replace all files from `C:\Users\{username}\AppData\Roaming\Wox\Plugins\WoxDictionary` with [the new release](https://github.com/harrynull/WoxDictionary/releases/download/v1.0.2/dist.zip).

**Comment by jcpeterson** [comment]
Wow, thanks! Will test soon.

**Comment by jcpeterson** [comment]
It works, thanks again!

![image](https://user-images.githubusercontent.com/8072691/63215959-f1f1f100-c0fb-11e9-907f-41b29c437dfc.png)
