### ISSUE TITLE
没看懂第四步如何操作：“打开设置，配置 API tokens.”

### ISSUE THREAD

**Issue by sparklau** [harrynull/WoxDictionary#8]
插件已经安装好，但是没看懂第四步“打开设置，配置 API tokens.”应当如何操作，可以详细介绍吗？

**Comment by harrynull** [comment]
右键任务栏Wox图标（或者唤出Wox输入settings） - Plugin/插件菜单 - 选中 Dictionary 插件 - 填写两个tokens (第一个用于中译英，第二个用于近义词) - 重启 Wox

**Comment by sparklau** [comment]
谢谢回复。
前边这些步骤都清楚，问题在get tokens上。
- 爱词霸的打开是403提示
- 同义词那个需要填写“Describe your application.””Website/app store URL“，应该如何填呢？

**Comment by harrynull** [comment]
爱词霸403可能是爱词霸方面的问题，只能等待他们修复。

同义词那个可以填写本项目repo。或者可以试试填写自己的github profile，然后description写自用。

sparklau <notifications@github.com> 于 2020年3月6日周五 01:20写道：

**Comment by sparklau** [comment]
已经拿到并填了API Key，查询后网站也显示我的Request了。不过可能是网络原因，Wox上没显示结果，只看到下方滚动条的反馈。

就不继续折腾了。谢谢您的回复。
